name: Build and Release

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          pyinstaller -n "cloudflare-ddns.exe" app.py 
        shell: cmd

      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-artifact
          path: build/app/cloudflare-ddns.exe

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-artifact
          path: .
      
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: /home/runner/work/cloudflare-ddns/cloudflare-ddns/build/app/cloudflare-ddns.exe
          token: ${{ secrets.GH_TOKEN }}